#!/bin/bash
# Add an issue or PR to the project board — Generated by /handoff setup
# Usage: .agents/scripts/handoff/add-to-project.sh <issue-number>
# Example: .agents/scripts/handoff/add-to-project.sh 42
#
# Returns the project item ID on success.

set -e

ISSUE_NUM="$1"

if [ -z "$ISSUE_NUM" ]; then
  echo "Usage: $0 <issue-number>" >&2
  exit 1
fi

REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')
ISSUE_URL="https://github.com/$REPO/issues/$ISSUE_NUM"

ITEM_ID=$(gh project item-add 1 --owner matt-sergi --url "$ISSUE_URL" --format json | jq -r '.id')

if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "null" ]; then
  echo "Failed to add issue #$ISSUE_NUM to project board" >&2
  exit 1
fi

echo "$ITEM_ID"
