#!/bin/bash
# Check all work queues in priority order — Generated by /handoff setup
# Usage: .agents/scripts/handoff/check-work-queues.sh
#
# Queries the three work priority queues (In Review, Needs Revision, Ready)
# and outputs them with labeled sections. Agents use this at the start of
# each work cycle to find the highest-priority task.
#
# Output format:
#   === In Review ===
#   #42: Fix login bug
#   === Needs Revision ===
#   === Ready ===
#   #15: Add utility scripts
#
# Empty sections have no items listed (just the header).

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=== In Review ==="
"$SCRIPT_DIR/query-by-status.sh" "In Review"

echo "=== Needs Revision ==="
"$SCRIPT_DIR/query-by-status.sh" "Needs Revision"

echo "=== Ready ==="
"$SCRIPT_DIR/query-by-status.sh" "Ready"
