#!/bin/bash
# Optimistic lock: set issue status only if current status matches expected — Generated by /handoff setup
# Usage: .agents/scripts/handoff/check-and-set-status.sh <issue-number> <expected-status> <new-status>
# Example: .agents/scripts/handoff/check-and-set-status.sh 42 "Ready" "In Progress"
#
# Exit codes:
#   0 — Status matched and was updated
#   1 — Status did not match (another agent changed it)
#   2 — API error

set -e

ISSUE_NUM="$1"
EXPECTED="$2"
NEW_STATUS="$3"

if [ -z "$ISSUE_NUM" ] || [ -z "$EXPECTED" ] || [ -z "$NEW_STATUS" ]; then
  echo "Usage: $0 <issue-number> <expected-status> <new-status>" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Read current status from board
# shellcheck disable=SC2016
QUERY='
query($cursor: String) {
  user(login: "matt-sergi") {
    projectV2(number: 1) {
      items(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          fieldValueByName(name: "Status") {
            ... on ProjectV2ItemFieldSingleSelectValue { name }
          }
          content {
            ... on Issue { number }
            ... on PullRequest { number }
          }
        }
      }
    }
  }
}
'

CURRENT_STATUS=""
CURSOR=""
while true; do
  if [ -z "$CURSOR" ]; then
    RESULT=$(gh api graphql -f query="$QUERY") || exit 2
  else
    RESULT=$(gh api graphql -f query="$QUERY" -f cursor="$CURSOR") || exit 2
  fi

  FOUND=$(echo "$RESULT" | jq -r --argjson num "$ISSUE_NUM" '
    .data.user.projectV2.items.nodes[]
    | select(.content.number == $num)
    | .fieldValueByName.name
  ')

  if [ -n "$FOUND" ] && [ "$FOUND" != "null" ]; then
    CURRENT_STATUS="$FOUND"
    break
  fi

  HAS_NEXT=$(echo "$RESULT" | jq -r '.data.user.projectV2.items.pageInfo.hasNextPage')
  if [ "$HAS_NEXT" != "true" ]; then
    break
  fi

  CURSOR=$(echo "$RESULT" | jq -r '.data.user.projectV2.items.pageInfo.endCursor')
done

if [ -z "$CURRENT_STATUS" ]; then
  echo "Issue #$ISSUE_NUM not found on project board" >&2
  exit 2
fi

CURRENT_LOWER=$(echo "$CURRENT_STATUS" | tr '[:upper:]' '[:lower:]')
EXPECTED_LOWER=$(echo "$EXPECTED" | tr '[:upper:]' '[:lower:]')

if [ "$CURRENT_LOWER" != "$EXPECTED_LOWER" ]; then
  echo "CONFLICT: Issue #$ISSUE_NUM is \"$CURRENT_STATUS\", expected \"$EXPECTED\". Another agent may have claimed it." >&2
  exit 1
fi

# Status matches — proceed with update
"$SCRIPT_DIR/set-issue-status.sh" "$ISSUE_NUM" "$NEW_STATUS"
