#!/bin/bash
# Check out a PR branch with a deconflicting local name for review — Generated by /handoff setup
# Usage: .agents/scripts/handoff/checkout-pr-for-review.sh <pr-number> <agent-id>
# Example: .agents/scripts/handoff/checkout-pr-for-review.sh 188 joe/agent-1
#
# Creates local branch: review/<agent-id>/pr-<pr-number>
# Fails if working tree is not clean.

set -e

PR_NUM="$1"
AGENT_ID="$2"

if [ -z "$PR_NUM" ] || [ -z "$AGENT_ID" ]; then
  echo "Usage: $0 <pr-number> <agent-id>" >&2
  exit 1
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: Working tree is not clean. Commit or stash changes before reviewing." >&2
  exit 1
fi

git fetch origin

HEAD_BRANCH=$(gh pr view "$PR_NUM" --json headRefName --jq '.headRefName')

if [ -z "$HEAD_BRANCH" ] || [ "$HEAD_BRANCH" = "null" ]; then
  echo "Could not get branch name for PR #$PR_NUM" >&2
  exit 1
fi

REVIEW_BRANCH="review/$AGENT_ID/pr-$PR_NUM"

git checkout -b "$REVIEW_BRANCH" "origin/$HEAD_BRANCH"

echo "Checked out PR #$PR_NUM on local branch: $REVIEW_BRANCH"
