#!/bin/bash
# Check if an issue's blockers are all resolved — Generated by /handoff setup
# Usage: .agents/scripts/handoff/check-blockers.sh <issue-number>
# Example: .agents/scripts/handoff/check-blockers.sh 42
#
# Parses the issue body for "Blocked by #N" lines (one per line, strict format).
# Checks each referenced issue's state.
#
# Exit codes:
#   0 — Unblocked (all referenced issues are closed, or no blocker lines found)
#   1 — Blocked (at least one referenced issue is still open; prints open blockers to stderr)

set -e

ISSUE_NUM="$1"

if [ -z "$ISSUE_NUM" ]; then
  echo "Usage: $0 <issue-number>" >&2
  exit 1
fi

BODY=$(gh issue view "$ISSUE_NUM" --json body --jq '.body')

# Extract issue numbers from "Blocked by #N" lines (strict format, case-insensitive)
BLOCKERS=$(echo "$BODY" | sed -n 's/^[[:space:]]*[Bb]locked by #\([0-9][0-9]*\).*/\1/p')

if [ -z "$BLOCKERS" ]; then
  exit 0
fi

BLOCKED=0
for blocker in $BLOCKERS; do
  STATE=$(gh issue view "$blocker" --json state --jq '.state')
  if [ "$STATE" != "CLOSED" ]; then
    echo "Blocked by #$blocker ($STATE)" >&2
    BLOCKED=1
  fi
done

exit $BLOCKED
