#!/bin/bash
# Clean up task branches that have been merged — Generated by /handoff setup
# Usage: .agents/scripts/handoff/cleanup-merged-branches.sh <base-branch>
# Example: .agents/scripts/handoff/cleanup-merged-branches.sh joe/agent-1

set -e

BASE_BRANCH="$1"

if [ -z "$BASE_BRANCH" ]; then
  echo "Usage: $0 <base-branch>" >&2
  exit 1
fi

MERGED_BRANCHES=$(git branch --merged "$BASE_BRANCH" | grep -E "task/" || true)

if [ -z "$MERGED_BRANCHES" ]; then
  echo "No merged task branches to clean up"
  exit 0
fi

for branch in $MERGED_BRANCHES; do
  branch=$(echo "$branch" | xargs)
  echo "Deleting merged branch: $branch"
  git branch -d "$branch"
done

echo "Cleanup complete"
