#!/bin/bash
# Find the epic branch for a given issue number — Generated by /handoff setup
# Usage: .agents/scripts/handoff/find-epic-branch.sh <ISSUE_NUMBER>
# Example: .agents/scripts/handoff/find-epic-branch.sh 42
#
# Fetches from origin and looks for a branch matching epic/ISSUE-<N>-*.
# Outputs the branch name (without origin/ prefix) if found.
# Exits non-zero if no epic branch exists for the given issue.

set -e

NUMBER="$1"

if [ -z "$NUMBER" ]; then
  echo "Usage: $0 <issue-number>" >&2
  echo "Example: $0 42" >&2
  exit 1
fi

git fetch origin --quiet 2>/dev/null || true

BRANCH=$(git branch -r --list "origin/epic/ISSUE-${NUMBER}-*" | head -1 | sed 's|^ *origin/||')

if [ -z "$BRANCH" ]; then
  exit 1
fi

echo "$BRANCH"
