#!/bin/bash
# Find the open PR that closes a given issue number — Generated by /handoff setup
# Usage: .agents/scripts/handoff/find-pr-for-issue.sh <issue-number>
# Example: .agents/scripts/handoff/find-pr-for-issue.sh 42
#
# Matches: Closes #N, Fixes #N, Resolves #N (case-insensitive)

set -e

ISSUE_NUM="$1"

if [ -z "$ISSUE_NUM" ]; then
  echo "Usage: $0 <issue-number>" >&2
  exit 1
fi

PR_NUM=$(gh pr list --state open --json number,body | \
  jq -r ".[] | select(.body | test(\"(?i)(closes|fixes|resolves) #$ISSUE_NUM\")) | .number" | head -1)

if [ -z "$PR_NUM" ]; then
  echo "No open PR found for issue #$ISSUE_NUM" >&2
  exit 1
fi

echo "$PR_NUM"
