#!/bin/bash
# Get the HEAD commit SHA for a given PR — Generated by /handoff setup
# Usage: .agents/scripts/handoff/get-pr-commit-sha.sh <pr-number>

set -e

PR_NUM="$1"

if [ -z "$PR_NUM" ]; then
  echo "Usage: $0 <pr-number>" >&2
  exit 1
fi

COMMIT_SHA=$(gh pr view "$PR_NUM" --json headRefOid --jq '.headRefOid')

if [ -z "$COMMIT_SHA" ] || [ "$COMMIT_SHA" = "null" ]; then
  echo "Could not get commit SHA for PR #$PR_NUM" >&2
  exit 1
fi

echo "$COMMIT_SHA"
