#!/bin/bash
# Get the autonomy level for an issue from its labels — Generated by /handoff setup
# Usage: .agents/scripts/handoff/get-issue-autonomy.sh <issue-number> <default-level>
# Example: .agents/scripts/handoff/get-issue-autonomy.sh 42 full
#
# Returns: full, plan, or supervised

set -e

ISSUE_NUM="$1"
DEFAULT="$2"

if [ -z "$ISSUE_NUM" ]; then
  echo "Usage: $0 <issue-number> [default-level]" >&2
  exit 1
fi

if [ -z "$DEFAULT" ]; then
  DEFAULT="full"
fi

LABELS=$(gh issue view "$ISSUE_NUM" --json labels --jq '.labels[].name')

for label in $LABELS; do
  case "$label" in
    "autonomy:full")       echo "full"; exit 0 ;;
    "autonomy:plan")       echo "plan"; exit 0 ;;
    "autonomy:supervised") echo "supervised"; exit 0 ;;
  esac
done

echo "$DEFAULT"
