#!/bin/bash
# Get project board ITEM_ID for a given issue/PR number — Generated by /handoff setup
# Usage: .agents/scripts/handoff/get-item-id.sh <number>

set -e

NUMBER="$1"

if [ -z "$NUMBER" ]; then
  echo "Usage: $0 <issue-or-pr-number>" >&2
  exit 1
fi

# shellcheck disable=SC2016
QUERY='
query($cursor: String) {
  user(login: "matt-sergi") {
    projectV2(number: 1) {
      items(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          id
          content {
            ... on Issue { number }
            ... on PullRequest { number }
          }
        }
      }
    }
  }
}
'

CURSOR=""
while true; do
  if [ -z "$CURSOR" ]; then
    RESULT=$(gh api graphql -f query="$QUERY")
  else
    RESULT=$(gh api graphql -f query="$QUERY" -f cursor="$CURSOR")
  fi

  ITEM_ID=$(echo "$RESULT" | jq -r --argjson num "$NUMBER" '
    .data.user.projectV2.items.nodes[]
    | select(.content.number == $num)
    | .id
  ')

  if [ -n "$ITEM_ID" ] && [ "$ITEM_ID" != "null" ]; then
    echo "$ITEM_ID"
    exit 0
  fi

  HAS_NEXT=$(echo "$RESULT" | jq -r '.data.user.projectV2.items.pageInfo.hasNextPage')
  if [ "$HAS_NEXT" != "true" ]; then
    break
  fi

  CURSOR=$(echo "$RESULT" | jq -r '.data.user.projectV2.items.pageInfo.endCursor')
done

echo "Item #$NUMBER not found on project board" >&2
exit 1
