#!/bin/bash
# List all agent worktrees and their status — Generated by /handoff setup
# Usage: .agents/scripts/handoff/list-worktrees.sh
#
# Output: <worktree-path> <branch> <status>
# Status is one of: active, clean, dirty, missing

set -e

git worktree list --porcelain | awk '
  /^worktree / { path = $2 }
  /^branch /   { branch = $2; sub(/^refs\/heads\//, "", branch) }
  /^$/ {
    if (path != "" && branch != "") {
      print path, branch
    }
    path = ""; branch = ""
  }
  END {
    if (path != "" && branch != "") {
      print path, branch
    }
  }
' | while read -r wt_path wt_branch; do
  if [ ! -d "$wt_path" ]; then
    echo "$wt_path $wt_branch missing"
  elif [ -n "$(git -C "$wt_path" status --porcelain 2>/dev/null)" ]; then
    echo "$wt_path $wt_branch dirty"
  else
    echo "$wt_path $wt_branch clean"
  fi
done
