#!/bin/bash
# Post a comment on an issue — Generated by /handoff setup
# Usage: .agents/scripts/handoff/post-issue-comment.sh <issue-number> <body>
# Example: .agents/scripts/handoff/post-issue-comment.sh 42 "**Agent: joe/agent-1** ..."

set -e

ISSUE_NUM="$1"
BODY="$2"

if [ -z "$ISSUE_NUM" ] || [ -z "$BODY" ]; then
  echo "Usage: $0 <issue-number> <body>" >&2
  exit 1
fi

gh issue comment "$ISSUE_NUM" --body "$BODY"
