#!/bin/bash
# Post a line-specific review comment on a PR — Generated by /handoff setup
# Usage: .agents/scripts/handoff/post-pr-comment.sh <pr-number> <commit-sha> <path> <line> <body>
# Example: .agents/scripts/handoff/post-pr-comment.sh 42 abc123 src/main.js 15 "Missing null check"
#
# For multi-line comments, use: <start_line>-<end_line> for the line argument
# Example: .agents/scripts/handoff/post-pr-comment.sh 42 abc123 src/main.js 10-15 "This block needs refactoring"

set -e

PR_NUM="$1"
COMMIT_SHA="$2"
FILE_PATH="$3"
LINE_ARG="$4"
BODY="$5"

if [ -z "$PR_NUM" ] || [ -z "$COMMIT_SHA" ] || [ -z "$FILE_PATH" ] || [ -z "$LINE_ARG" ] || [ -z "$BODY" ]; then
  echo "Usage: $0 <pr-number> <commit-sha> <path> <line|start-end> <body>" >&2
  echo "  Single line:  $0 42 abc123 src/main.js 15 \"Missing null check\"" >&2
  echo "  Multi-line:   $0 42 abc123 src/main.js 10-15 \"Refactor this block\"" >&2
  exit 1
fi

REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')

if echo "$LINE_ARG" | grep -q '-'; then
  START_LINE=$(echo "$LINE_ARG" | cut -d'-' -f1)
  END_LINE=$(echo "$LINE_ARG" | cut -d'-' -f2)
  gh api "repos/$REPO/pulls/$PR_NUM/comments" \
    -f body="$BODY" \
    -f commit_id="$COMMIT_SHA" \
    -f path="$FILE_PATH" \
    -f subject_type="line" \
    -f side="RIGHT" \
    -f start_side="RIGHT" \
    -F start_line="$START_LINE" \
    -F line="$END_LINE"
else
  gh api "repos/$REPO/pulls/$PR_NUM/comments" \
    -f body="$BODY" \
    -f commit_id="$COMMIT_SHA" \
    -f path="$FILE_PATH" \
    -f subject_type="line" \
    -f side="RIGHT" \
    -F line="$LINE_ARG"
fi
