#!/bin/bash
# Prune baseline-covered entries from agent worktree settings — Generated by /handoff setup
# Usage: .agents/scripts/handoff/prune-local-permissions.sh
#
# Reads .agents/config.yml to discover agent worktrees.
# Reads .claude/settings.json as the shared baseline.
# For each worktree's .claude/settings.local.json, removes entries
# that are already covered by the shared baseline.
# Deletes the file entirely if no entries remain.
#
# Exit codes:
#   0 — Prune complete
#   1 — Missing config or settings file

set -e

# Resolve PROJECT_ROOT from primary git worktree
PROJECT_ROOT=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')

CONFIG="$PROJECT_ROOT/.agents/config.yml"
SETTINGS="$PROJECT_ROOT/.claude/settings.json"

if [ ! -f "$CONFIG" ]; then
  echo "Cannot find .agents/config.yml" >&2
  exit 1
fi

if [ ! -f "$SETTINGS" ]; then
  echo "Cannot find .claude/settings.json" >&2
  exit 1
fi

# Read baseline permissions as JSON array
BASELINE_JSON=$(jq '.permissions.allow // []' "$SETTINGS")

# Extract worktree paths from config.yml
WORKTREES=()
while IFS= read -r line; do
  wt=$(echo "$line" | sed 's/.*worktree:[[:space:]]*//' | tr -d '"' | tr -d "'" | sed 's/[[:space:]]*$//')
  if [ -n "$wt" ]; then
    WORKTREES+=("$wt")
  fi
done < <(grep 'worktree:' "$CONFIG" 2>/dev/null || true)

PRUNED_TOTAL=0

for wt_rel in "${WORKTREES[@]}"; do
  wt_path="$PROJECT_ROOT/$wt_rel"
  local_settings="$wt_path/.claude/settings.local.json"

  if [ ! -f "$local_settings" ]; then
    continue
  fi

  original_count=$(jq '.permissions.allow // [] | length' "$local_settings")

  if [ "$original_count" -eq 0 ]; then
    continue
  fi

  # Filter out entries that appear in the shared baseline
  updated=$(jq --argjson baseline "$BASELINE_JSON" '
    .permissions.allow = (
      .permissions.allow // [] | map(
        select(. as $p | ($baseline | any(. == $p)) | not)
      )
    )
  ' "$local_settings")

  remaining=$(printf '%s' "$updated" | jq '.permissions.allow | length')
  pruned=$((original_count - remaining))

  if [ "$pruned" -eq 0 ]; then
    continue
  fi

  if [ "$remaining" -eq 0 ]; then
    # Check if the file has other keys besides permissions.allow
    has_other=$(printf '%s' "$updated" | jq '
      del(.permissions.allow) |
      if .permissions == {} or .permissions == null then del(.permissions) else . end |
      length
    ')

    if [ "$has_other" -eq 0 ]; then
      rm "$local_settings"
      echo "Removed $local_settings (all $pruned entries covered by baseline)"
    else
      printf '%s\n' "$updated" | jq 'del(.permissions.allow) |
        if .permissions == {} or .permissions == null then del(.permissions) else . end' \
        > "$local_settings"
      echo "Pruned all $pruned allow entries from $local_settings"
    fi
  else
    printf '%s\n' "$updated" > "$local_settings"
    echo "Pruned $pruned entries from $local_settings ($remaining remaining)"
  fi

  PRUNED_TOTAL=$((PRUNED_TOTAL + pruned))
done

echo "Total pruned: $PRUNED_TOTAL"
