#!/bin/bash
# Query project board items by status — Generated by /handoff setup
# Usage: .agents/scripts/handoff/query-by-status.sh "Status Name"
# Example: .agents/scripts/handoff/query-by-status.sh "In Review"

set -e

STATUS="$1"

if [ -z "$STATUS" ]; then
  echo "Usage: $0 <status>" >&2
  echo "Example: $0 \"In Review\"" >&2
  exit 1
fi

# shellcheck disable=SC2016
QUERY='
query($cursor: String) {
  user(login: "matt-sergi") {
    projectV2(number: 1) {
      items(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          fieldValueByName(name: "Status") {
            ... on ProjectV2ItemFieldSingleSelectValue { name }
          }
          content {
            ... on Issue { number title }
            ... on PullRequest { number title }
          }
        }
      }
    }
  }
}
'

CURSOR=""
while true; do
  if [ -z "$CURSOR" ]; then
    RESULT=$(gh api graphql -f query="$QUERY")
  else
    RESULT=$(gh api graphql -f query="$QUERY" -f cursor="$CURSOR")
  fi

  echo "$RESULT" | jq -r --arg status "$STATUS" '
    .data.user.projectV2.items.nodes[]
    | select((.fieldValueByName.name // "") | ascii_downcase == ($status | ascii_downcase))
    | select(.content.number != null)
    | "#\(.content.number): \(.content.title)"
  '

  HAS_NEXT=$(echo "$RESULT" | jq -r '.data.user.projectV2.items.pageInfo.hasNextPage')
  if [ "$HAS_NEXT" != "true" ]; then
    break
  fi

  CURSOR=$(echo "$RESULT" | jq -r '.data.user.projectV2.items.pageInfo.endCursor')
done
