#!/bin/bash
# Move an issue to a status column on the project board — Generated by /handoff setup
# Usage: .agents/scripts/handoff/set-issue-status.sh <issue-number> <status>
# Example: .agents/scripts/handoff/set-issue-status.sh 42 "In Progress"
#
# Valid statuses:
#   Backlog, Ready, In Progress, In Review, In Human Review, Needs Revision, Done

set -e

ISSUE_NUM="$1"
STATUS="$2"

if [ -z "$ISSUE_NUM" ] || [ -z "$STATUS" ]; then
  echo "Usage: $0 <issue-number> <status>" >&2
  echo "Valid statuses: Backlog, Ready, In Progress, In Review, In Human Review, Needs Revision, Done" >&2
  exit 1
fi

STATUS_LOWER=$(echo "$STATUS" | tr '[:upper:]' '[:lower:]')

case "$STATUS_LOWER" in
  "backlog")           OPTION_ID="d961d47f" ;;
  "ready")             OPTION_ID="4ea244e1" ;;
  "in progress")       OPTION_ID="3de44a86" ;;
  "in review")         OPTION_ID="6ce3c407" ;;
  "in human review")   OPTION_ID="f856bf31" ;;
  "needs revision")    OPTION_ID="1110bda5" ;;
  "done")              OPTION_ID="bf13acef" ;;
  *)
    echo "Unknown status: $STATUS" >&2
    echo "Valid statuses: Backlog, Ready, In Progress, In Review, In Human Review, Needs Revision, Done" >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ITEM_ID=$("$SCRIPT_DIR/get-item-id.sh" "$ISSUE_NUM")
PROJECT_ID=$(gh project view 1 --owner matt-sergi --format json | jq -r '.id')

gh project item-edit --project-id "$PROJECT_ID" --id "$ITEM_ID" \
  --field-id PVTSSF_lAHOD51gHs4BPYw9zg9z2JI --single-select-option-id "$OPTION_ID"

echo "Moved issue #$ISSUE_NUM to \"$STATUS\""
