#!/bin/bash
# Fetch origin, checkout agent base branch, merge main — Generated by /handoff setup
# Usage: .agents/scripts/handoff/sync-agent-branch.sh <agent-id>
# Example: .agents/scripts/handoff/sync-agent-branch.sh joe/agent-1
#
# The agent-id IS the base branch name (e.g., joe/agent-1)

set -e

AGENT_ID="$1"

if [ -z "$AGENT_ID" ]; then
  echo "Usage: $0 <agent-id>" >&2
  exit 1
fi

echo "Syncing agent branch: $AGENT_ID"

git fetch origin
git checkout "$AGENT_ID"
git merge origin/main --no-edit

echo "Agent branch $AGENT_ID synced with origin/main"
